### ISSUE TITLE
[Feature]: use a DSN for credentials

### ISSUE THREAD

**Issue by dkarlovi** [Unleash/unleash-client-symfony#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the new feature

Currently, the credentials are passed individually, like so

```yaml
unleash_symfony_client:
  app_url: http://localhost:4242/api
  instance_id: myCoolApp-Server1
  app_name: myCoolApp
```

A better approach would be to allow a single string to represent all three values, a so called DSN (at least that's a common name in Symfony ecosystem for this concept).

```yaml
unleash_symfony_client:
  url: http://localhost:4242/api&instance_id=myCoolApp-Server1&app_name=myCoolApp
```

# Why?

It makes this a single piece of data which is easier to manage as a secret (for example in k8s). This approach is very common otherwise, for example Symfony itself uses it for cache and messenger, Doctrine uses it for the DB connection string, etc.

### Describe alternatives you've considered (optional)

You can store JSON in the secret and then unwrap it, but that's cumbersome to manage.

### Additional context (optional)

In some cases, you're billed per secret used so keeping it all together reduces cost.
