### ISSUE TITLE
[Bug]: passing DSN via env(file) doesn't work

### ISSUE THREAD

**Issue by dkarlovi** [Unleash/unleash-client-symfony#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In #68, support for late binding of DSN (via env var) was added.

This works in scenarios like so

```yaml
# UNLEASH_DSN=<DSN>
unleash_client:
    dsn: '%env(UNLEASH_DSN)%'
```

It doesn't work for scenarios where env vars use [Symfony's env var processors](https://symfony.com/doc/current/configuration/env_var_processors.html):

```yaml
# UNLEASH_DSN_FILE=/run/secrets/unleash_dsn
# file /run/secrets/unleash_dsn contains DSN
unleash_client:
    dsn: '%env(trim:file:UNLEASH_DSN_FILE)%'
```

The latter is a pretty common workflow when running apps with [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/).

### To reproduce

See example before.

### Version

0.11.382

### Expected behavior

Env var used for DSN is correctly processed with (built in or custom) processors, which Symfony does by default.

### Additional context (optional)

Version number is not an error, it seems the repo creates a new tag on each action?
